# Generated by Django 5.0.1 on 2024-01-17 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.IntegerField()),
                ('building', models.CharField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('technician', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='streaming_transition.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('built_in', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('smart_device', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reccomendation', models.TextField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='streaming_transition.apartment')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='streaming_transition.visit')),
            ],
        ),
    ]
