# Generated by Django 5.0.1 on 2024-01-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_transition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
