# Generated by Django 5.0.1 on 2024-01-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_transition', '0003_apartment_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='comments',
        ),
    ]
