# Generated by Django 5.0.1 on 2024-01-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_transition', '0005_rename_reccomendation_device_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='comments',
            new_name='comment',
        ),
    ]
