# Generated by Django 5.0.1 on 2024-01-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_transition', '0006_rename_comments_visit_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='complete',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
