# Generated by Django 5.0.1 on 2024-01-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_transition', '0007_alter_visit_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='complete',
            field=models.TimeField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
