# Generated by Django 5.0.1 on 2024-01-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_transition', '0008_alter_visit_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='visit',
        ),
    ]
