# Generated by Django 5.0.1 on 2024-01-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_transition', '0009_remove_device_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='complete',
            new_name='time_completed',
        ),
    ]
