# Generated by Django 5.0.1 on 2024-01-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_transition', '0010_rename_complete_visit_time_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time_completed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
